version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5460:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  web:
    container_name: api_rinha_v01
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rinha_api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
