# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST') { localhost } %>
  username: <%= ENV.fetch('POSTGRES_USER') { postgres } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { postgres } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rinha_api_v01_development

test:
  <<: *default
  database: rinha_api_v01_test

production:
  <<: *default
  database: rinha_api_v01_production
  username: rinha_api_v01
  password: <%= ENV["RINHA_API_V01_DATABASE_PASSWORD"] %>
